#name of workflow
name: Production workflow

#When workflow is triggered
on:
  push:
    tags:
      - "v*"

#jobs to carry out
jobs:
  deploy:
    #Operating system to run job on
    runs-on: ubuntu-latest
    #Steps in job
    steps:
      #Get code from repo
      - name: Checkout code
        uses: actions/checkout@v1
      # Install NodeJS
      - name: Uses Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      #Deploy to Netlify using our production secrets
      - name: Deploy to netlify
        uses: netlify/actions/cli@main
        env:
          NETLIFY_AUTH_TOKEN: ${{secrets.NETLIFY_AUTH_TOKEM}}
          NETLIFY_SITE_ID: ${{secrets.NETLIFY_SITE_ID}}
        with:
          args: deploy --dir=build --prod
          secretes: '["NETLIFY_AUTH_TOKEN", "NETLIFY_SITE__ID"]'
